meta_product_name: "Thread Films"
meta_title: "Thread Films - Independent Film Production Company London"
meta_description: "We create everything from 15 second bite sized films to documentaries, hype reels, branded content and everything in between. Whether it’s corporate, commercial or charitable – we work with organisations and people to bring their story to life. Our charitable focus is helping military veterans tell their stories."
meta_image: "thread_meta.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
